### PR TITLE
Fixes for upstream

### PR DESCRIPTION
**Pull request by dwagelaar**
- Fixes NPE on null CRL server response (server down?)
- Fixes various unclosed resources

### CODE REVIEW

**Comment by fcorneli** [comment]
FYI... werd veroorzaakt doordat de Root CA 4 CRL zo nu en dan blijkbaar "leeg" was.

**Comment by fcorneli** [comment]
Looking good. Will merge within the next release of jTrust. Thanks.

**Comment by fcorneli** [comment]
Issue was just an NPE on a debug logging message.
https://github.com/e-Contract/jtrust/commit/8570557a9d277a27110f8eea49c91419305962bd

**Comment by dwagelaar** [comment]
The latest commits were intended for the consumer code to determine that OCSP/CRL server failure was the cause of the "no trust" error. This allows us to keep our systems online when third party servers are down.

**Pull request closed without merging**
